# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_auto_20170718_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adult',
            name='membership_status',
        ),
        migrations.RemoveField(
            model_name='child',
            name='membership_status',
        ),
    ]
