# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0006_family_membership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families_adult_related', related_query_name='families_adults', to='families.Family'),
        ),
        migrations.AlterField(
            model_name='child',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families_child_related', related_query_name='families_childs', to='families.Family'),
        ),
    ]
