# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-22 02:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0010_auto_20170720_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='region',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='country', chained_model_field='country', default=1, help_text='State', on_delete=django.db.models.deletion.CASCADE, to='cities_local.Region'),
        ),
    ]
