# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0014_auto_20170722_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_local.Country'),
        ),
        migrations.AlterField(
            model_name='family',
            name='region',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='country', chained_model_field='country', help_text='State', on_delete=django.db.models.deletion.CASCADE, to='cities_local.Region'),
        ),
    ]
