# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0018_auto_20170722_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_local.City'),
        ),
        migrations.AlterField(
            model_name='family',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_local.Country'),
        ),
        migrations.AlterField(
            model_name='family',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_local.Region'),
        ),
    ]
