# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0019_auto_20170723_1915'),
    ]

    operations = [
    ]
