# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0020_auto_20170725_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GroupAdultMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families.Adult')),
            ],
        ),
        migrations.CreateModel(
            name='GroupChildMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families.Child')),
            ],
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='MemRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_role', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name_plural': 'Membership Roles',
            },
        ),
        migrations.AddField(
            model_name='groupchildmember',
            name='member_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.MemRole'),
        ),
        migrations.AddField(
            model_name='groupadultmember',
            name='member_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.MemRole'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.GroupType'),
        ),
    ]
